require 'nokogiri'
require 'open-uri'
require 'pow'
require 'rubygems'
require 'valuable'
require 'yaml'

require 'ngpod_scraper/ngpod_scraper'
require 'ngpod_scraper/client'
require 'ngpod_scraper/photo'
require 'ngpod_scraper/photo_page'
